fixtures:
  repositories:
    mysql:
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'c57600e4f0aedddb7cb92bd113495a139a15ec68'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
  symlinks:
    openfire: "#{source_dir}"
